github.com:
    users:
        dantas-barreto:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: dantas-barreto
