[window]
	opacity = 0.9
	blur = true

[font]
	normal = { family = "3270NerdFontMono", style = "Regular" }
	bold = { style = "Bold" }
	italic = { style = "Italic" }
	bold_italic = { style = "Bold Italic" }
	size = 9.5
	offset = { x = 0, y = 0 }
	glyph_offset = { x = 0, y = 0 }
	builtin_box_drawing = true
